version: '0.9'
services:
  news_downloader_pro:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:news_downloader_pro
    environment:
      - TZ=Asia/Shanghai
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      - TZ=Asia/Shanghai
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

    # mongo-express:
    #   image: mongo-express
    #   restart: always
    #   ports:
    #     - 8081:8081
    #   environment:
    #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #     ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
    #     ME_CONFIG_MONGODB_URL: mongodb://root:12345678@mongo:27017/
