version: '4.0'

services:

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    command: --auth
    volumes:
      - ./mongo/initdb:/docker-entrypoint-initdb.d
      - ./mongo/datadir:/data/db
      - ./mongo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MINGO_INITDB_DATABASE: test001
      TZ: Asia/Shanghai

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 80:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
  # engine:
  #   build: /opt/news_downloader_pro
  #   image: news_downloader_pro:v0.9
  #   # restart: always
  #   command:
  #     [
  #       "python",
  #       "/opt/news_downloader_pro/res/news_downloader_pro/main.py"
  #     ]
