version: '4.0'

services:

  # mongo:
  #   image: mongo:5.0
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 12345678

  engine:
    build: /opt/news_downloader_pro
    image: news_downloader_pro:v0.9
    restart: always
    command: [ "cat", "dockerfile" ]
