version: '3'

services:

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # command: --auth
    volumes:
      - ./mongo/initdb:/docker-entrypoint-initdb.d
      - ./mongo/datadir:/data/db
      - ./mongo/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      # MINGO_INITDB_DATABASE: demo001
      TZ: Asia/Shanghai

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 1999:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678

  engine:
    build: .
    image: news_downloader:v0.9
    depends_on:
      - mongodb
    command: [ "python", "main.py" ]
    stdin_open: true
    tty: true
